spring:
  h2:
    console:
      enabled: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true


  datasource:
    url: jdbc:h2:mem:db?serverTimezone=Asia/Seoul;MODE=MYSQL
    username: sa
    password:

logging:
  level:
    org:
      hibernate:
        SQL: debug