= HoseokLog API DOCS
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:sectnums:
:docinfo: shared-head

== 게시글

=== 게시글 등록
==== 성공
operation::post/create/success[snippets='request-fields,response-fields,http-request,http-response']
==== 실패
operation::post/create/success[snippets='request-fields']
operation::post/create/fail/emptyTitleAndContent[snippets='response-fields']
===== 게시글 제목을 입력하지 않는 경우
operation::post/create/fail/emptyTitle[snippets='http-request,http-response']
===== 게시글 내용을 입력하지 않는 경우
operation::post/create/fail/emptyContent[snippets='http-request,http-response']
===== 게시글 제목에 허용되지 않은 키워드를 사용한 경우
operation::post/create/fail/disallowedKeywordInTitle[snippets='http-request,http-response']

=== 게시글 단건 조회
==== 성공
operation::post/findOne/success[snippets='path-parameters,response-fields,http-request,http-response']
==== 실패
operation::post/findOne/fail/notFoundId[snippets='path-parameters,response-fields']
===== 게시글 id가 존재하지 않는 경우
operation::post/findOne/fail/notFoundId[snippets='http-request,http-response']

=== 게시글 전체 조회
==== 성공
operation::post/findAll/success[snippets='query-parameters,response-fields,http-request,http-response']

=== 게시글 수정
==== 성공
operation::post/updatePost/success[snippets='path-parameters,http-request,http-response']
==== 실패
operation::post/updatePost/fail/notFoundPost[snippets='path-parameters,response-fields']
===== 게시글 id가 존재하지 않는 경우
operation::post/updatePost/fail/notFoundPost[snippets='http-request,http-response']

=== 게시글 삭제
==== 성공
operation::post/delete/success[snippets='path-parameters,http-request,http-response']
==== 실패
operation::post/delete/fail/notFoundPost[snippets='path-parameters,response-fields']
===== 게시글 id가 존재하지 않는 경우
operation::post/delete/fail/notFoundPost[snippets='http-request,http-response']